spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduate_project?useSSL=false
    username: root
    password: Sh_951753.
server:
  port: 8085
  context-path: /graduateProject