spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduate_project?useSSL=false
    username: root
    password: Sh_951753.
server:
  port: 8080
#  context-path: /graduate_project
  context-path: /
path: "http://127.0.0.1:8020/myProject/"